# Generated by Django 4.0.1 on 2023-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('distance_base_price', models.FloatField()),
                ('distance_additional_price', models.FloatField()),
                ('time_multiplier_factor', models.FloatField()),
                ('waiting_charge', models.FloatField()),
            ],
        ),
    ]
