# Generated by Django 4.0.1 on 2023-07-29 21:21

from django.db import migrations


def update_default_rows(apps, schema_editor):
    Configuration = apps.get_model('configuration', 'Configuration')

    default_rows = [
        {'day': 'Monday', 'distance_base_price': 10.0, 'distance_additional_price': 2.0, 'time_multiplier_factor': 1.5, 'waiting_charge': 5.0},
        {'day': 'Tuesday', 'distance_base_price': 11.0, 'distance_additional_price': 2.2, 'time_multiplier_factor': 1.4, 'waiting_charge': 5.0},
        {'day': 'Wednesday', 'distance_base_price': 12.0, 'distance_additional_price': 2.4, 'time_multiplier_factor': 1.3, 'waiting_charge': 5.0},
        {'day': 'Thursday', 'distance_base_price': 13.0, 'distance_additional_price': 2.6, 'time_multiplier_factor': 1.2, 'waiting_charge': 5.0},
        {'day': 'Friday', 'distance_base_price': 14.0, 'distance_additional_price': 2.8, 'time_multiplier_factor': 1.1, 'waiting_charge': 5.0},
        {'day': 'Saturday', 'distance_base_price': 15.0, 'distance_additional_price': 3.0, 'time_multiplier_factor': 1.0, 'waiting_charge': 5.0},
        {'day': 'Sunday', 'distance_base_price': 16.0, 'distance_additional_price': 3.2, 'time_multiplier_factor': 0.9, 'waiting_charge': 5.0},
    ]

    for row_data in default_rows:
        Configuration.objects.update_or_create(day=row_data['day'], defaults=row_data)

class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_created_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RunPython(update_default_rows),
    ]
