# Generated by Django 4.0.1 on 2023-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_created_add_configuration_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='base_waiting_time',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='configuration',
            name='distance_base_km',
            field=models.FloatField(default=1),
        ),
    ]
